# DIRS
RIOTBASE = ../RIOT

# APP NAME
APPLICATION = Teste1

# MODULES
USEMODULE += ztimer_usec
USEMODULE += ztimer_msec
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_ipv6
USEMODULE += gnrc_sixlowpan_default
USEMODULE += gnrc_udp
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += gnrc_txtsnd
USEMODULE += gnrc_pktdump
USEMODULE += ibr_node_sensor_shield

# FLAGS
CFLAGS += 

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# Comment this out to disable code in RIOT that does safety checking
# which is not needed in a production environment but helps in the
# development process:
DEVELHELP ?= 1

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1




include $(RIOTBASE)/Makefile.include











